site:
  title: Website
  groups:
    - title: Sites
      items:
        - title: Home
          icon: "https://icons.getbootstrap.com/assets/icons/house.svg"
          link: "https://alexanderschau.com/"
        - title: Projects
          icon: "https://icons.getbootstrap.com/assets/icons/kanban.svg"
          link: "https://alexanderschau.com/projects"
        - title: Blog
          icon: "https://icons.getbootstrap.com/assets/icons/book.svg"
          site: ./blog.yaml
        - title: Imprint
          icon: "https://icons.getbootstrap.com/assets/icons/file-text.svg"
          link: "https://alexanderschau.com/imprint"
